// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hello.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SayHelloHandler service

type SayHelloHandlerService interface {
	SayHello(ctx context.Context, in *HelloReq, opts ...client.CallOption) (*HelloResp, error)
}

type sayHelloHandlerService struct {
	c    client.Client
	name string
}

func NewSayHelloHandlerService(name string, c client.Client) SayHelloHandlerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &sayHelloHandlerService{
		c:    c,
		name: name,
	}
}

func (c *sayHelloHandlerService) SayHello(ctx context.Context, in *HelloReq, opts ...client.CallOption) (*HelloResp, error) {
	req := c.c.NewRequest(c.name, "SayHelloHandler.SayHello", in)
	out := new(HelloResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SayHelloHandler service

type SayHelloHandlerHandler interface {
	SayHello(context.Context, *HelloReq, *HelloResp) error
}

func RegisterSayHelloHandlerHandler(s server.Server, hdlr SayHelloHandlerHandler, opts ...server.HandlerOption) error {
	type sayHelloHandler interface {
		SayHello(ctx context.Context, in *HelloReq, out *HelloResp) error
	}
	type SayHelloHandler struct {
		sayHelloHandler
	}
	h := &sayHelloHandlerHandler{hdlr}
	return s.Handle(s.NewHandler(&SayHelloHandler{h}, opts...))
}

type sayHelloHandlerHandler struct {
	SayHelloHandlerHandler
}

func (h *sayHelloHandlerHandler) SayHello(ctx context.Context, in *HelloReq, out *HelloResp) error {
	return h.SayHelloHandlerHandler.SayHello(ctx, in, out)
}
